server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:sqlserver://AlimentandoOFuturo.mssql.somee.com;databaseName=AlimentandoOFuturo;encrypt=true;trustServerCertificate=true
    username: alimentandoofuturo
    password: "@ITB123456"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false

# Configuração JWT
jwt:
  secret: alimentandoofuturo2024secretkeysupersecure
  expiration: 28800000 # 8 horas em millisegundos

# Configuração CORS
cors:
  allowed-origins:
    - http://localhost:5173
    - https://*.netlify.app
    - https://*.netlify.com
    - https://alimentando-o-futuro.netlify.app

# Configuração de Email
mail:
  host: smtp.office365.com
  port: 587
  username: rm94720@estudante.fieb.edu.br
  password: ${MAIL_PASSWORD:senha_temporaria}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

logging:
  level:
    com.alimentandoofuturo: INFO
    org.springframework.security: WARN
    org.springframework.web.cors: DEBUG