server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://AlimentandoOFuturo.mssql.somee.com;databaseName=AlimentandoOFuturo;encrypt=true;trustServerCertificate=true
    username: alimentandoofuturo
    password: @ITB123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

logging:
  level:
    com.alimentandoofuturo: DEBUG
    org.springframework.security: DEBUG